### ISSUE TITLE
Adding Filter by regions (e.g., North America, Europe, Asia, etc.) 

### ISSUE THREAD

**Issue by rohitg00** [scraly/developers-conferences-agenda#1077]
This feature will allow users to filter conferences based on their geographical regions, enabling easier navigation and more targeted event searches. Implementing this filter will help users quickly find conferences relevant to their location or regions of interest.

## Steps to Reproduce:
- Navigate to the developer conferences agenda table.
- Observe the absence of a region-based filter option.

## Expected Behavior:

- Users should be able to filter the conferences displayed in the agenda table by selecting a specific region. This will refine the list to show only those conferences that are held in the selected region.

## Actual Behavior:
- Currently, there is no option to filter conferences by regions, making it less convenient for users looking for geographically relevant events.

## Proposed Solution:
- Add a dropdown menu or a set of checkboxes for regions (e.g., North America, Europe, Asia, etc.) in the agenda table interface.
- Implement the backend logic to filter the displayed conferences based on the selected regions.
- Ensure that the filtering functionality is smooth and does not impact the performance of the agenda table.

**Comment by scraly** [comment]
Hi,
for the moment a user can simply add an event in a location with a city and a country.
If we want a filter by continent, we have a first problem to solve:
How to easily connect/link/attach a country to a continent?

If an API exist with that information, maybe we can create a map/a json file like the geolocation's one with this information?
And we need to update the map when a new event is added.

@jespino What do u think?

**Comment by jespino** [comment]
I'm thinking now that we can have mapping Country->Continent json, and then a linter that checks that every single country in the events list is in the Country->Continent map, that way we can then filter by contenting. The drawback is, every event that includes a new country, requires a manual Country->Continent mapping entry. Also, the first PR is going to take a bit of time for that, but I think can be done without much effort.

**Comment by jespino** [comment]
We can also name them "Regions" instead of continents, to reduce areas, like subcontinent like north America and south america.
