### ISSUE TITLE
InfoQ Dev Summit Boston. June 9-10, 2025

### ISSUE THREAD

**Issue by ianrobins** [scraly/developers-conferences-agenda#1219]
**Title**: InfoQ Dev Summit Boston. June 9-10, 2025.
**Short Title**: InfoQ Dev Summit Boston 2025
**Date**: June 9-10, 2025.
**Venue**: Boston University, George Sherman Union, Boston, MA

**Short Description**:
InfoQ Dev Summit Boston (June 9-10, 2025) brings together senior developers for two days of actionable technical insights, peer-validated approaches, and community connections - all focused on practical takeaways for today’s development challenges. With over 25 sessions from active software practitioners, gain real-world strategies on scalable architectures, security, AI, and more.

**Long Description**:
InfoQ Dev Summit Boston 2025 (June 9-10) is a two-day conference tailored for senior software developers seeking practical solutions to complex challenges. Join a community of active practitioners for in-depth sessions on the critical issues facing software today, covering architectures, resilience, platform engineering, and emerging AI/ML use cases. With over 25 talks led by active software developers, each session is crafted to deliver actionable takeaways you can apply directly to your projects.

Expect insights on:
● Scalable architectures, security in software, and resilience for SREs and developers
● Innovative approaches to multicloud practices and platform engineering
● Real-world strategies and peer-driven advice from leading software practitioners

Designed to prioritize learning over hype, InfoQ Dev Summit Boston 2025 is where “practitioners talk to practitioners,” fostering genuine connections and real-world learning without sales pitches.

_“At InfoQ Dev Summit Boston, we'll provide senior developers with practical solutions to today's most pressing challenges. This conference isn't about hype or theory. It's about learning from peers who are actively solving complex problems. The insights and strategies shared are rooted in real-world experiences, giving you the clarity and direction to make well-informed decisions in an ever-evolving landscape.”_ Eder Ignatowicz, InfoQ Dev Summit Boston 2025 Chair, Senior Principal Software Engineer and Architect @RedHat

**Team discounts**.
Team discounts are available to enhance collaborative learning, leading to impactful project decisions and alignment with your dev roadmap. Teams as small as 3 attendees working for the same company are eligible for a group discount. For more details, email info@devsummit.infoq.com and mention the size of the group.

InfoQ Dev Summit Boston 2025 provides senior software developers with a unique opportunity to learn transformative insights that will directly impact their immediate development roadmap and decision-making processes.

Please feel free to contact us with any questions at info@devsummit.infoq.com

**Website Link**: https:/devsummit.infoq.com/boston2025_medialisting
**Tickets Link**: https:/devsummit.infoq.com/boston2025_medialisting/tickets

**Event inquiries**: info@devsummit.infoq.com
**Sales inquiries**: sales@devsummit.infoq.com

**Facebook**: https:/www.facebook.com/InfoQdotcom
**LinkedIn**: https:/www.linkedin.com/company/infoq/
**Instagram**: https:/www.instagram.com/infoqdotcom/
**Mastodon**: https:/ techhub.social/@infoq

**Press & Media Contact**:
Ian Robins
Marketing Director
C4Media, creators of InfoQ & QCon
Email: ian@c4media.com
General Marketing Enquiries: marketing@c4media.com

**About Infoq Dev Summit Munich by InfoQ**:
InfoQ presents InfoQ Dev Summit Munich. For over 19 years, InfoQ has guided senior software development teams with peer-validated, trustworthy insights in adopting new technologies and practices.

**Comment by scraly** [comment]
Added :)
