### ISSUE TITLE
Scroll back to Top button

### ISSUE THREAD

**Issue by scraly** [scraly/developers-conferences-agenda#1264]
It could be an easy first issue to add a button that allows ro scroll back to the Top easily for the List view.

**Comment by jack-samo10000** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a Scroll to Top button to the ListView component to improve navigation for users, especially when dealing with long lists of events. The button appears when the user scrolls down and disappears when at the top. Styling is consistent with the existing design.

You can review changes in this commit: https://github.com/jack-samo10000/scraly-developers-conferences-agenda-1264/commit/fb0dde6966745dba543a7ba96a02cc34ff33c2e3.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by iBerserker89** [comment]
I made a bakc to top button. Hope it is good enough.

**Comment by scraly** [comment]
Fixed by #1266  :)

**Comment by scraly** [comment]
Thanks @iBerserker89

**Comment by iBerserker89** [comment]
Thank you! ill keep up and try to help more if i can.
