### ISSUE TITLE
[Feature Idea] Caldav endpoint

### ISSUE THREAD

**Issue by micheelengronne** [scraly/developers-conferences-agenda#143]
I am throwing here the idea of a caldav endpoint.

It would ease the integration in our calendar apps.

As we are all very busy, this issue is a placeholder if anyone one day has time for that.

Thanks.

**Comment by alexandre-touret** [comment]
It could be nice to have an ICS endpoint too.
Perhaps, it could be available through a github pages web site.

**Comment by jicowan** [comment]
+1 would be great if we could import this list into Google calendar or another web based calendar.

**Comment by jeanphibaconnais** [comment]
Hi, it would be a great feature. I would like to make this on the nantes.community project. If I succeed to make this, I will tell you and check how make it here.

**Comment by HanzCEO** [comment]
> It could be nice to have an ICS endpoint too. Perhaps, it could be available through a github pages web site.

I'm interested in making a GitHub page for this repo. Opening a draft PR soon 🙌

**Comment by scraly** [comment]
An .ics endpoint is not available thanks to @HanzCEO  :) 

https://developers.events/

**Comment by andypiper** [comment]
Neat!

One thing that might be useful to go further, is if this supported an ongoing subscription to an endpoint, rather than a one-off download of the calendar. That way, the calendar app can just update the list of events in the background, instead of a user having to visit, download, and re-import each time.

**Comment by HanzCEO** [comment]
I don't refer this issue to be closed because I was implementing ICS in the
GitHub page, not CalDav. I think one could implement CalDav in GitHub
Pages, at least that's how I understand CalDav.
