### ISSUE TITLE
[Enhancement] Having a different list for CFPs ordered by date

### ISSUE THREAD

**Issue by davinkevin** [scraly/developers-conferences-agenda#205]
The current project can be really useful if, as a speaker, you want to check all the ongoing CFP. 
Maybe a different list/view just for CFPs can be helpful.

Kiss 😚

**Comment by scraly** [comment]
Now the list of CFP is available in JSON (first step :-)).
Link: https://developers.events/all-cfps.json

**Comment by scraly** [comment]
Do you want a good news?
Finally, you can filter to have only CFP and with the list view you can have the list ordered by date
