### ISSUE TITLE
Incorrect dates for QCon London

### ISSUE THREAD

**Issue by ianrobins** [scraly/developers-conferences-agenda#242]
Hello,

The dates that you have for QCon London are incorrect here https://github.com/scraly/developers-conferences-agenda

The dates should be 27-29 March 2023. Please can these be corrected?

**Comment by scraly** [comment]
Hi,
I just fixed the QCon London dates.
For the next time, don't ehsitate to create yourself a PR (Pull Request) in order to fix the information you have seen :).

Thanks.
