### ISSUE TITLE
I think this repository needs CONTRIBUTING.md

### ISSUE THREAD

**Issue by HanzCEO** [scraly/developers-conferences-agenda#290]
So, recently a GitHub Action workflow were made and it fails just because of a small flaw. To minimize this, CONTRIBUTING.md guide plays a good role. It is also a good addition to this community-based repo.

Maybe the guide should consist of:
 - Writing syntax
 - Difference of archive files and README.md
 - How to make PRs

**Comment by fmerian** [comment]
Thanks, @HanzCEO! I like this idea, too.

Could be something like this:
``` markdown
# Contributing

We welcome every contribution!

## Guidelines
* All changes must be made in a branch and submitted as a Pull Request (PR)
* Add one event per PR
   * Make sure the PR title is in the format of `Add conference-name`
* Add the link: `* date: [conference-name](https://example.com/) - city, state (country)`
   * If there's an on-going Call For Proposals (CFP), please specify it at the end of the link: `<a href="https://example.com/"><img alt="CFP conference-name" src="https://img.shields.io/static/v1?label=CFP&message=until%20DD-MONTH-YYYY&color=green"></a>`
* Check your spelling and grammar
* Remove any trailing whitespace

Thanks!
```

**Comment by HanzCEO** [comment]
Hi @fmerian, mind writing a PR for that? That would definitely be helpful. Amazing work!

**Comment by scraly** [comment]
Now the repository have a contributing guide, thanks :)
