### ISSUE TITLE
[Feature Request] Publish ICS File

### ISSUE THREAD

**Issue by geoffcline** [scraly/developers-conferences-agenda#295]
Thanks to the great work of @HanzCEO you can download a .ics file of these events. 🎉 

However, this file is generated by the client each time. Integration with things like iCal and Outlook requires the ics file at a fixed url. 

I propose generating the ics file with a github action after each commit to main, and serving this from github pages. The existing code could be reused to do this https://github.com/scraly/developers-conferences-agenda/blob/f8eb9eb7d3ce385bf2a70b6669cecdd69494a304/page/src/App.js#L42

**Comment by jonatan-ivanov** [comment]
Could you please edit the title of the issue? "[Feature Request]" is not very descriptive.

**Comment by geoffcline** [comment]
Whoops! Sorry. 🎄🎅🏻🧠

**Comment by marcwrobel** [comment]
I contribute to a project, https://github.com/endoflife-date/endoflife.date/, where a similar feature was implemented using a Jekyll plugin (https://github.com/endoflife-date/endoflife.date/blob/master/_plugins/create-icalendar-files.rb).

The same thing could be done here using a python script launched after the `all-events.json` file generation : https://github.com/scraly/developers-conferences-agenda/blob/4f558bb75a25993b611df328049da0121a5c1695/.github/workflows/ghpages.yml#L31.

**Comment by sylvainmetayer** [comment]
Hi, I'd like to work on this one, as I'm interested to add a subscription in my calendar too. 

I've started as draft PR, I'll try to update it during the week and keep you updated.

**Comment by scraly** [comment]
thanks :-)
