### ISSUE TITLE
Update date for PolyCloud

### ISSUE THREAD

**Issue by GridexX** [scraly/developers-conferences-agenda#297]
Hello @rverchere, thanks for sharing the PolyCloud Conference
I'm a student at Polytech Montpellier and currently working at [r2devop](https://r2devops.io) !

This year the conference will be on Sunday 27th mai, as mentionned on the new version of the site:https://polycloud.fr/

**Comment by GridexX** [comment]
By the way, the CFP is open: https://conference-hall.io/public/event/OR1ldOA5G0ASoizWvVbO
We will soon release a new version of the site with all information :smile:

**Comment by rverchere** [comment]
Oh, sorry for the mistake, I'll update it!

**Comment by scraly** [comment]
thanks both of you :)
