### ISSUE TITLE
Sunny tech à Paris ?

### ISSUE THREAD

**Issue by giulbia** [scraly/developers-conferences-agenda#30]
Bonjour,

Je crois qu'il y a une erreur pour la ville de Sunny Tech, c'est à Montpellier, non ?

Merci pour ce projet en tout cas !

Bien à vous

**Comment by scraly** [comment]
Oui c'est a Montpellier, j'ai vu l'erreur mais pas corrigé encore, merci du rappel 🙂

**Comment by scraly** [comment]
Fix and Closed
