### ISSUE TITLE
2 Delphi conferences

### ISSUE THREAD

**Issue by DeveloppeurPascal** [scraly/developers-conferences-agenda#36]
Hi

Please add this dates to the agenda:

Foren-Tage 2019, https://forentage.de, September 20-21 2019, Mannheim (Germany)
EKON, https://entwickler-konferenz.de, October 28-30 2019, Dusseldorf (Germany)
 
Thanks

**Comment by scraly** [comment]
Should be added for 2020
Thanks 🙂
