### ISSUE TITLE
World map?

### ISSUE THREAD

**Issue by Pierstoval** [scraly/developers-conferences-agenda#420]
I recently discovered this project, and I was wondering whether it was possible to use the current data to publish them on a world map?

I'm familiar with Leaflet and OpenLayers, if you need someone to take care of the rendering part.

However, I'm not familiar with how the repository is maintained, all I would need is the actual data to display in a geographic-compatible way, such as the address, or at least the city.

Can we collaborate?

Edit: I just saw #415 , and if it is merged, the parser will now be made in JS, then I think it's a good opportunity to make it call Nominatim or another API to get the geolocation of every conference so that the web app can display them in a world map. WDYT?

**Comment by Damien-VS** [comment]
I believe the locations are ... sometimes unreliable.

And if we're going to add more complex entries, we're going to have other problems (validation, too complex for users, etc ...)
IMHO, we might as well input the thing with json / yaml directly if this direction is taken

**Comment by Pierstoval** [comment]
As we have the city of some events, we might just use Nominatim's Geocoding API to inject coordinates at build time based on the city, this would retrieve a latitude/longitude tuple that we can use in any map

**Comment by scraly** [comment]
now we have a map view :)
