### ISSUE TITLE
[Enhancement] More different colors between days with conferences and days without conferences in the calendar display

### ISSUE THREAD

**Issue by philippart-s** [scraly/developers-conferences-agenda#424]
The calendar is very cool.
I think it will be more readable if the days where there are no conferences are not grayed out like the days with conferences.

Maybe choose different colors to represent the presence of conference or not instead of a grey gradient (and it will more accessible 😉)

**Comment by scraly** [comment]
I think gray is cool for colorblind people because even if we can see colors, they can't, but yes I love colors too ^^.

**Comment by philippart-s** [comment]
Yes but I'm not sure that colorblind people see gradients very well.
I'm not an expert but I think there are some colors adopted to colorblind people or use some pictos to identify the days with conf and days without conf (perhaps just the number of confs on the day, some emojis, ...).

It was just an idea you can close if it's not a good idea 😉

**Comment by scraly** [comment]
In order to be compliant with everyone it should be awesome to have a normal mode with colors and an accessible mode like today with gray :-).

**Comment by glaforge** [comment]
I agree with @philippart-s 

The different shades of gray indicate the amount of events on each day.
The lightest gray leads us to think that there are events (but maybe just one) on each day. But that's not the case.
I suggest that days without events have a totally white background. No shade of gray at all.

For colorblindness, different colors would be problematic, indeed. 
But as long as we have just white for no-events, and some shades (gray or color) for days with events, it's fine.

**Comment by gouz** [comment]
My propositions:

Grey mode: 
![image](https://user-images.githubusercontent.com/219936/234229860-c80af579-31cb-4d05-827c-42317f92a7c6.png)

Color mode: (like rainbow, a legend will be added)
![image](https://user-images.githubusercontent.com/219936/234230007-5065823a-3a29-4f8f-902f-9143d774346b.png)

What do you think @glaforge @philippart-s ?

**Comment by gouz** [comment]
Yes, a toggle button is here to activate the color mode. Per default it will keep the grey levels.
In the images, if no event, then the day is white

**Comment by glaforge** [comment]
Here's what it looks like with my change:

<img width="424" alt="Screenshot 2023-04-25 at 11 12 36" src="https://user-images.githubusercontent.com/47907/234230905-000748c8-35ac-4d8d-a172-8826f0a80c28.png">

**Comment by gouz** [comment]
![Screenshot_20230425-111539](https://user-images.githubusercontent.com/219936/234231977-1b20315b-1250-489d-b8e1-230686655f59.png)
![Screenshot_20230425-111509](https://user-images.githubusercontent.com/219936/234231986-a145610e-5b1c-473f-90b4-3c8e0b3a01ac.png)

**Comment by scraly** [comment]
I love both ideas :-)

<img width="420" alt="image" src="https://user-images.githubusercontent.com/2543381/234231510-4f07f961-4e63-4ddc-9119-4142dffb6178.png">
vs
<img width="157" alt="image" src="https://user-images.githubusercontent.com/2543381/234231442-86b31a7e-8e9b-426c-8905-328c07989174.png">

I think the second one can be more helpful for colorblind people and for all people :-) 
The grays are more contrasted 👍

**Comment by glaforge** [comment]
But I also like the other proposal with strong contrast too.

**Comment by scraly** [comment]
You both found the way to help the calendar to be more visible and understable ❤️ 

Thinking about it, with this new contrast and the day with a white background for the no event cases, having a calendar with colors can complicate understanding, because you will have to look several times at the legend, whereas the:
- no color: no event
- more or less contrasting grey: there are more or fewer events

I think it meets the criteria

and we are colorblind compliant :-)

**Comment by philippart-s** [comment]
I agree, for me the main point to be more readable is to have no color when there is no conference.
Keep the grey color with contrast is, I think, more intuitive than "learn" a legend to know the meaning of each color.
