### ISSUE TITLE
Add QCon New York to Developer Conferences

### ISSUE THREAD

**Issue by ianrobins** [scraly/developers-conferences-agenda#433]
Hello, 

I tried to create a new pull request as advised but I was not able too.

Please can you add QCon New York to your conference list on: Developer Conferences

I have included our event listing below. If you need anything else please let me know.

All the best

Hannah

Title: QCon New York International Software Development Conference. June 13-15, 2023.
Short Title: QCon New York 2023
Dates: June 13-15, 2023 
Venue: New York Marriott at the Brooklyn Bridge, 333 Adams St, Brooklyn, NY 11201, USA

Short Description:
QCon New York is an international software development conference for senior software engineers, software architects, and team leads. Find practical inspiration (not product pitches) from software leaders deep in the trenches creating software, scaling architectures and fine-tuning their technical leadership to help you make the right decisions. 

Long Description:
QCon New York, the international software development conference for senior software engineers, software architects, and team leads is returning to the Big Apple.  

Between June 13-15 at the New York Marriott at the Brooklyn Bridge, software leaders driving innovation in software engineering and architecture will come together for 3 days of real-world technical talks, practical advice, and actionable insights. Find practical inspiration (not product pitches) from software leaders deep in the trenches creating software, scaling architectures, and fine-tuning their technical leadership to help you make the right decisions. 

QCon New York will focus on innovations and emerging trends in the software development industry. Deep-dive with world-class software leaders on the patterns, practices, and use cases leveraged by early adopter companies. Provisional topics covered at QCon New York include: 
Modern Data Architecture & Engineering
Architectures You've Always Wondered About 
Doing Platform Engineering Well 
21st Century Language Platforms
Connecting Distributed Systems: APIs done right
Designing Modern Reliable Architectures
Resilience Engineering - Culture as a System Requirement 
MLOps - Production & Delivery for ML Platforms
Next-Gen Fintech: Performance, Complexity & Privacy
Next in Cloud Native Development
Optimizing Teams for Fast Flow 
Resilient Security: Architecture & Software Supply Chain
Architectural Blueprints Of Real World Machine Learning Systems
Staff+ Engineering: New Skills, New Challenges 
Building Globally Distributed Systems: Patterns, Pitfalls, and Trade-Offs

“QCon is a conference that creates opportunities for any developer in the world to talk to talented programmers who use leading-edge technology in their projects and are ready to communicate their experience. QCon inspires!” Alina Lapina, QCon New York Attendee, Senior Developer @Experis Ciber

With practitioner-driven content, case studies, and technical talks, QCon will provide you with actionable insights and skills that you can take back to your teams.

At QCon, you’ll always find:
Senior software practitioners first.
Real-world technical talks.
No hidden marketing, no sales pitches, no hype.
Speakers hand-picked by an international program committee.
‘We Care’ experience: healthy food, healthy environment, strict code of conduct.

[Attending QCon New York](https://qconnewyork.com/?utm_source=qcon&utm_medium=email&utm_campaign=pastattendeesjan25ny23) in Brooklyn provides a unique opportunity to learn, build connections and explore one of the most vibrant and dynamic cities in the world. Connect with speakers and peers, attend group problem-solving unconference sessions, and join the conference social events.  It's a chance to take your professional development to the next level while experiencing all that New York has to offer. 
 
Build better-connected teams in the heart of New York.

With hybrid and remote working becoming the norm, team connectedness has become more important than ever. QCon New York brings together international software development teams to connect over new ideas to current challenges, get clarity on emerging tech decisions, and build relationships that extend beyond the conference. Join QCon as a team and save with exclusive discounts!

Level-up on the topics that matter the most right now, solve your complex engineering challenges and get clarity on software decisions, workflows, and roadmaps. Don’t miss out on real-world insights to help you adopt the right technologies and practices. 

Website Link: https://qconnewyork.com/medialisting 
Tickets Link: https://qconnewyork.com/medialisting/tickets

Event inquiries: [info@qconnewyork.com](mailto:info@qconnewyork.com)  
Sales inquiries: [sales@qconferences.com](mailto:sales@qconferences.com)

Facebook: https://www.facebook.com/QCon/ 
LinkedIn: https://www.linkedin.com/company/qcon-conferences/ 
Instagram: https://www.instagram.com/qconconferences/ 
Flickr: https://www.flickr.com/photos/qconpictures/collections/ 
Mastodon: https://techhub.social/@qcon 

Press & Media Contact: 
Hannah Pinchbeck
Marketing Manager
C4Media, creators of InfoQ & QCon
Email: [hannah@c4media.com](mailto:hannah@c4media.com)
General Marketing Enquiries: [marketing@c4media.com](mailto:marketing@c4media.com)

About QCon by InfoQ: 
We've been helping software development teams adopt new technologies and practices for over 17 years. The driving force behind every QCon conference is our passion to accelerate the software side of human progress.

Senior software developers rely on QCon and InfoQ to keep ahead of the adoption curve. One of the main reasons senior software engineers, software architects, and team leads tell us they keep coming back to QCon and InfoQ is because they trust the information provided and selected by their peers. Join a global professional engineering community and adopt the right software innovations and practices.

**Comment by scraly** [comment]
Added :) 
https://github.com/scraly/developers-conferences-agenda/commit/dbeed6b06635a1bb32bf0a9d069a6193824e501d
