### ISSUE TITLE
QCon San Francisco International Software Development Conference. 

### ISSUE THREAD

**Issue by ianrobins** [scraly/developers-conferences-agenda#486]
I am excited to announce the return of QCon San Francisco (October 2-6), the international software development conference for senior software engineers.

I wondered whether it would be possible to please have these events listed on your website?

Please see the below listing for your consideration.

Title: QCon San Francisco International Software Development Conference. Oct 2-6, 2023. In-person or Video-Only Pass to watch recordings later.
Short Title: QCon San Francisco 2023;  In-person or Video-Only Pass.
Dates: Conference: Oct 2-4, 2023; Workshops: Oct 5-6, 2023
Venue: Hyatt Regency San Francisco, 5 Embarcadero Ctr, San Francisco, CA 94111, United States

Short Description:
QCon San Francisco is an international software development conference for senior software engineers, software architects, and team leads. Attend in-person at the Hyatt Regency, San Francisco, or access professionally edited recordings after the conference with a Video-Only Pass. 

Long Description:
QCon San Francisco, the international software development conference for senior software engineers, software architects, and team leads is returning to San Francisco. Attend in-person at the Hyatt Regency, San Francisco or access professionally edited recordings after the conference with a Video-Only Pass. 

Between October 2-6, software leaders driving innovation in software engineering and architecture will come together for 3 days of real-world technical talks, practical advice, and actionable insights. The conference will be followed by 2-days of hands-on workshops, where you can deep-dive into specific topics and learn in an intimate setting.

Find practical inspiration (not product pitches) from software leaders deep in the trenches creating software, scaling architectures, and fine-tuning their technical leadership to help you make the right decisions. 

QCon San Francisco will focus on innovations and emerging trends in the software development industry. Deep-dive with world-class software leaders on the patterns, practices, and use cases leveraged by early adopter companies. Provisional topics covered at QCon San Francisco include: 
Architectures You've Always Wondered About
Performance: Designing and Tuning
Paving the Road: Enhancing Developer Productivity and Experience
Emerging AI and Machine Learning Trends
The Tech of FinTech
Staff+ Engineering in Practice
Debugging Production
Architecture in 2025
Building Security in Earlier
Building Modern Backends
Innovations in Data Engineering
Architecture with Sustainability in Mind
Remote and Hybrid Work: What Now?
Socially Conscious Software

"When I came to QCon, I found I could learn about new technologies and trends that, otherwise, I would not have come across (at least, for a while).” Austin Ward, Senior Software Engineer @Klaviyo, QCon San Francisco 2022 Attendee

With practitioner-driven content, case studies, and technical talks, QCon will provide you with actionable insights and skills that you can take back to your teams.

At QCon, you’ll always find:
Senior software practitioners first.
Real-world technical talks.
No hidden marketing, no sales pitches, no hype.
Speakers hand-picked by an international program committee.
‘We Care’ experience: healthy food, strict code of conduct.

Attend in-person for an immersive experience.
Attending QCon San Francisco in-person provides a unique opportunity to learn, build connections and explore one of the most vibrant and dynamic cities in the world. Connect with speakers and peers, attend group problem-solving unconference sessions, and join the conference social events.  It's a chance to take your professional development to the next level while experiencing all that QCon San Francisco has to offer. 

Build better-connected teams in the heart of San Francisco.
With hybrid and remote working becoming the norm, team connectedness has become more important than ever. QCon San Francisco brings together international software development teams to connect over new ideas to current challenges, get clarity on emerging tech decisions, and build relationships that extend beyond the conference. Join QCon as a team and save with exclusive discounts for both in-person and video-only experiences!

New for 2023! Video-Only Pass to access professionally edited conference recordings after the event.
QCon's Video-Only Pass is a flexible way for senior software developers and their teams to access professionally edited recordings after the conference. Access to video recordings will be available from Oct 20th.

Level-up on the topics that matter the most right now, solve your complex engineering challenges and get clarity on software decisions, workflows, and roadmaps. Don’t miss out on real-world insights to help you adopt the right technologies and practices. 

Website Link: https://qconsf.com/medialisting 
Tickets Link: https://qconsf.com/medialisting/tickets 

Event inquiries: [info@qconsf.com](mailto:info@qconsf.com) 
Sales inquiries: [sales@qconferences.com](mailto:sales@qconferences.com)

Facebook: https://www.facebook.com/QCon/ 
LinkedIn: https://www.linkedin.com/company/qcon-conferences/ 
Instagram: https://www.instagram.com/qconconferences/ 
Flickr: https://www.flickr.com/photos/qconpictures/collections/ 
Mastodon: https://techhub.social/@qcon 
Twitter: https://twitter.com/QConSF 

Press & Media Contact: 
Hannah Pinchbeck
Marketing Manager
C4Media, creators of InfoQ & QCon
Email: [hannah@c4media.com](mailto:hannah@c4media.com)
General Marketing Enquiries: [marketing@c4media.com](mailto:marketing@c4media.com)

About QCon by InfoQ: 
We've been helping software development teams adopt new technologies and practices for over 17 years. The driving force behind every QCon conference is our passion to accelerate the software side of human progress.

Senior software developers rely on QCon and InfoQ to keep ahead of the adoption curve. One of the main reasons senior software engineers, software architects, and team leads tell us they keep coming back to QCon and InfoQ is because they trust the information provided and selected by their peers. Join a global professional engineering community and adopt the right software innovations and practices.

**Comment by scraly** [comment]
Hi,
yes, as @fmerian already said (thanks :-) ), the event is already on the website
<img width="1380" alt="image" src="https://github.com/scraly/developers-conferences-agenda/assets/2543381/b02424a5-4e50-49b0-b374-1291a72e9a91">

If you decide to open the CFP, don't hesitate to create a Pull Request with the cfp link :)
