### ISSUE TITLE
Import Droidcon conferences

### ISSUE THREAD

**Issue by emartynov** [scraly/developers-conferences-agenda#537]
Hi, 

Thank you for the extended list of the conferences. I see there that the [Droidcon](https://www.droidcon.com/events/) events are entirely missed.
I can/will add them by hand. However, I wonder if it is possible to automate for the future syncs.

**Comment by scraly** [comment]
Hi
Yes for the moment it can be added by hand
About an automation, the listing is in a README file so maybe it's possible to add them with a scrapping or something else :)
