### ISSUE TITLE
[BUG] 🐛 October detailled view is empty

### ISSUE THREAD

**Issue by philippart-s** [scraly/developers-conferences-agenda#542]
The calendar view for October is empty:
![image](https://github.com/scraly/developers-conferences-agenda/assets/26224751/261f541b-b6fc-40d0-a3ca-6353e6d36dac)

**Comment by scraly** [comment]
Bien vu !!!

**Comment by HanzCEO** [comment]
Ouch, the page completely vaporized in an instant.

**Comment by scraly** [comment]
I see the problem 
fixing in progress :)

**Comment by scraly** [comment]
<img width="1233" alt="image" src="https://github.com/scraly/developers-conferences-agenda/assets/2543381/6c66c3fe-9e28-46c1-9a06-ad520680c511">
fixed :)
