### ISSUE TITLE
🆕 Adding DDD Europe 2024 to the list (with CFP deadline)

### ISSUE THREAD

**Issue by Mehdi-H** [scraly/developers-conferences-agenda#561]
Hello, I have opened a new PR to add DDD Europe 2024 conference to the list, here : #560 ❗ 

Can anyone review it, give me some feedback if necessary and validate it ? 

Thanks !

**Comment by scraly** [comment]
Hi
Maybe in the future I Will delete the emoji when filters will be added but for the moment it's good for me 🙂
