### ISSUE TITLE
QCon London (8-10 April, 2024): International Software Development Conference

### ISSUE THREAD

**Issue by ianrobins** [scraly/developers-conferences-agenda#582]
Hello,

I hope you're doing well?

I am excited to announce the return of QCon London, the international software development conference for senior software engineers.

I wondered whether it would be possible to have this event listed on your website?

Please see the below and attached listing for consideration.

Title: QCon London International Software Development Conference. April 8-10, 2024.

Short Title: QCon London 2024

Dates: April 8-10, 2024

Venue: The Queen Elizabeth II Conference Centre London (The QEII), Broad Sanctuary, Westminster, London, SW1P 3EE, United Kingdom

Short Description:

QCon London is an international software development conference for senior software engineers, software architects, and team leads. 

Long Description:

QCon London is an international software development conference for senior software engineers, software architects, and team leads. 

On April 8-10, 2024, senior software leaders driving innovation in software engineering and architecture will come together for 3 days of real-world technical talks, practical advice, and actionable insights. 

Find practical inspiration (not product pitches) from senior software leaders deep in the trenches creating software, scaling architectures, and fine-tuning their technical leadership to help you make the right decisions. 

Deep-dive with world-class software leaders on the patterns, practices, and use cases leveraged by early adopter companies. Tentative tracks at QCon London include: 

The Tech of FinTech

Debugging Production

The Paved Path: Unlocking Engineering Velocity

Architectures You've Always Wondered About

Designing for Resilience

Architecting for the Cloud

Staff+ Engineering Skills

Platform Engineering Done Well

Lessons in Building Organization Resilience

Deep Tech: Pushing the Boundaries of Tech

JVM Trends: Driving Developer Productivity & Performance

Languages of Infra: Beyond YAML

Emerging Trends in the Frontend

Modern ML: GenAI, Trust, & Path2Prod

Modern Data Engineering & Architectures

“QCon is like the SuperBowl of technology conferences - expertly curated tracks, aimed at experienced individuals. It's a wonderland for learning, meeting people, and just celebrating technology and the innovations in our industries. I leave the event with many things that I can take back and improve when back at work as well as being energized again. From the quality of the talks, the venue and organization, and the best keynotes daily, it's the highlight of my conference year!.” 

Richard Roché, Principal Engineer @Workhuman

With practitioner-driven content, case studies, and technical talks, QCon will provide you with actionable insights and skills that you can take back to your teams.

At QCon, you’ll always find:

Senior software practitioners first.

Real-world technical talks.

No hidden marketing, no sales pitches, no hype.

Speakers Hand-picked by an international program committee.

‘We Care’ experience: healthy food, healthy environment, strict code of conduct.

Attending QCon London provides a unique opportunity to learn, build connections and explore one of the most vibrant and dynamic cities in the world. Connect with speakers and peers, attend group problem-solving unconference sessions, and join the conference social events. It's a chance to take your professional development to the next level while experiencing all that QCon London has to offer. 

Build better-connected teams in the heart of London.

QCon London brings together international software development teams to connect over new ideas to current challenges, get clarity on emerging tech decisions, and build relationships that extend beyond the conference.

Join QCon as a team and save with exclusive discounts. Group discounts for groups of 10+ attendees are available now. Discounts for all other group sizes will be available starting January 17th, 2024.

For more details and to apply for a discount code, please contact [info@qconlondon.com](mailto:info@qconlondon.com) and mention the size of the group.

Level-up on the topics that matter the most right now, solve your complex engineering challenges, and get clarity on software decisions, workflows, and roadmaps. Don’t miss out on real-world insights to help you adopt the right technologies and practices. 

Is your company interested in connecting with senior developers and decision-makers? Explore sponsorship opportunities by emailing [sales@qconferences.com](mailto:sales@qconferences.com). 

For all other enquires please email [info@qconlondon.com](mailto:info@qconlondon.com).

Website Link: https://qconlondon.com/medialisting2024  

Tickets Link: https://qconlondon.com/medialisting2024/tickets   

Event enquiries:: [info@qconlondon.com](mailto:info@qconlondon.com) 

Sales enquiries: [sales@qconferences.com](mailto:sales@qconferences.com).

Facebook: https://www.facebook.com/QCon/ 

LinkedIn: https://www.linkedin.com/company/qcon-conferences/ 

Instagram: https://www.instagram.com/qconconferences/ 

Flickr: https://www.flickr.com/photos/qconpictures/collections/ 

Mastodon: https://techhub.social/@qcon 

X (Twitter) (QCon London): https://twitter.com/qconlondon 

Threads: https://www.threads.net/@qconconferences 

If you have any questions please do let me know and I look forward to hearing from you.

All the best,
Hannah Pinchbeck (she/her)

**Comment by fmerian** [comment]
hi @ianrobins, thanks for the suggestion!

for the record, @synodinos added the event in #578. we can close this issue @scraly :)
