### ISSUE TITLE
Add different views (not only calendar actual view)

### ISSUE THREAD

**Issue by scraly** [scraly/developers-conferences-agenda#614]
Few months ago, @HanzCEO had the idea to refactor/improve the existing website to not have only calendar view but also others views.

![image](https://github.com/scraly/developers-conferences-agenda/assets/2543381/ebfe956e-1489-47ce-b268-665271ee9f42)
![image](https://github.com/scraly/developers-conferences-agenda/assets/2543381/a6db9337-5614-4546-9980-199591fd7f24)
![image](https://github.com/scraly/developers-conferences-agenda/assets/2543381/471e3172-3a52-4a30-a8a4-40c5659d7ef7)

Thanks to these complex views, we can imagine to add also filters and CFP only toggle button.

**Comment by jespino** [comment]
I love the desing proposal, but looks like a heavy lifting, What do you think about doing it "gradually"? For example, adding the filtering bar at the left, and keep everything else the same. That is an interesting improvement but without changing the whole interface.

**Comment by scraly** [comment]
new list and map view thanks! :)
