### ISSUE TITLE
adding effects

### ISSUE THREAD

**Issue by harshsbhandari** [scraly/developers-conferences-agenda#645]
adding effects to arrow buttons and download button. @scraly I can fix this
![Screenshot (154)](https://github.com/scraly/developers-conferences-agenda/assets/73375087/d960dbf5-98ec-4948-87cd-b77e094ef2ae)

**Comment by scraly** [comment]
Yes it will be useful to add the hand icon during the hover in arrows buttons for example

**Comment by harshsbhandari** [comment]
> Yes it will be useful to add the hand icon during the hover in arrows buttons for example

Yes ma'am, can you please assign this issue to me

**Comment by scraly** [comment]
it's done, but you know you can do some PRs without be assigned :)

**Comment by harshsbhandari** [comment]
done the required changes

**Comment by scraly** [comment]
done :)
