### ISSUE TITLE
Add a filter for ClosedCaption events

### ISSUE THREAD

**Issue by scraly** [scraly/developers-conferences-agenda#671]
Now we have a filter section and a list view, we can have a useful feature: to be able to filter on only events with "closed captions" (very useful for deaf or hard of hearing speakers and attendees ❤️)

The idea visually is to have a new filter "Closed captions":
<img width="1402" alt="image" src="https://github.com/scraly/developers-conferences-agenda/assets/2543381/6f6b3f98-978d-476f-a8ae-0eddbf6771d9">

And to list only events with closed captions tag: 
<img width="151" alt="image" src="https://github.com/scraly/developers-conferences-agenda/assets/2543381/7bd69b14-98c8-42ef-8885-efbaf095c78a">

**Comment by scraly** [comment]
Maybe this feature can interest you @jespino ☺️
WDYT?

**Comment by jespino** [comment]
@scraly easy peasy ;) Some other filter that you want to add ?

**Comment by scraly** [comment]
Top, thanks!

I will think about other filters ☺️.
But the first one I have in my mind is a filter by country. If I want only the events in "France" for example or "USA". It can be relevant.
