### ISSUE TITLE
Run in CI geoCodes script and save the updated geocodes file

### ISSUE THREAD

**Issue by scraly** [scraly/developers-conferences-agenda#693]
Since PR, we have a file called [geolocations.json](https://github.com/scraly/developers-conferences-agenda/blob/main/page/src/misc/geolocations.json).
Now we need to add in the CI the execution of the `geoCodes.js` script that updated this file and then we need to store it in this repo.

**Comment by davidaparicio** [comment]
Interesting, I will give a look how to do it :)

**Comment by davidaparicio** [comment]
Aurélie, is it not already done on this [workflow](https://github.com/scraly/developers-conferences-agenda/blame/main/.github/workflows/ghpages.yml#L33) ?

**Comment by scraly** [comment]
I will add a check for that point :)
