### ISSUE TITLE
ViewMap: markers are not showing

### ISSUE THREAD

**Issue by scraly** [scraly/developers-conferences-agenda#695]
<img width="1397" alt="image" src="https://github.com/scraly/developers-conferences-agenda/assets/2543381/3bdc9ffa-33b3-4910-bfbc-3a657eb91f0e">

Markers images are not showing.
@jespino can you have. a look on it?

thanks :)

**Comment by jespino** [comment]
Checking it right away.

**Comment by scraly** [comment]
I think I have a little fix:

```
import icon from 'leaflet/dist/images/marker-icon.png';
import iconShadow from 'leaflet/dist/images/marker-shadow.png';
import { Icon } from 'leaflet'
const myIcon = new Icon({
 iconUrl: icon,
 shadowUrl: iconShadow
})
```

And assign the icon in the marker:
```
            <Marker icon={myIcon} position={[geolocations[loc].latitude, geolocations[loc].longitude]} key={loc}>
```

It works locally but don't know yet if it's works in production too.

**Comment by ankur-dahiya** [comment]
can i work on this issue ?

**Comment by scraly** [comment]
Fixed with #696 :-) 
<img width="1385" alt="image" src="https://github.com/scraly/developers-conferences-agenda/assets/2543381/e83af1f1-7235-4d9c-951b-ebf759dbd4ed">

But if you don't find the code correct, you can improve it, it's not a problem

**Comment by ankur-dahiya** [comment]
how can i improve it if issue is already closed ? by creating a new issue?

**Comment by jespino** [comment]
@ankur-dahiya you can create a PR directly, of if it is a suggestion, you can create an issue (or if you don't mind sending a PR as a "suggestion", that also normally works).

By the way, I already sent a PR to fix the positioning of the makers, that was a bit off, just in case that is what you want to fix.

**Comment by ankur-dahiya** [comment]
@jespino thx for the clarification my friend
