### ISSUE TITLE
Suggestion: Can we only show the Download Calendar button in the calendar view?

### ISSUE THREAD

**Issue by jespino** [scraly/developers-conferences-agenda#699]
To save some real state we can show only the "Download Calendar" button whenever we are in the Calendar view.

Also... maybe the calendar view is no longer the ideal view as de default one (Or maybe it is, but we now have other options)

**Comment by scraly** [comment]
Good idea to have only the calendar button(s) where we are in the calendar view.
About the second idea, I think we can wait a little, users will discover the new views and then I can ask to the users there favorite views :)

**Comment by jespino** [comment]
Totally fair. Let's wait until users have the time to taste it.

I'll submit a PR with the download calendar button hidden for non calendar views.
