### ISSUE TITLE
feat(ui): ability to search with more than one country

### ISSUE THREAD

**Issue by davinkevin** [scraly/developers-conferences-agenda#740]
Hello 👋 , 

First, like you already know, the project is very good and helpful for many people, so for that, thank you to the whole community behind the project!

My request is very simple, as a user, I would like to filter out elements not on **ONE** country but with multiple of them (Europe has a lot of countries 😅). 

The search module could have:

* `<select multiple>`, to select multiple countries
* a pre-filled list of countries selected based on another continent field ?
* a way to draw a shape on a map 🗺️ to restrict locations (geojson search…)
* something else… I'm definitely not a UI expert 😅. 

Thank you

**Comment by jespino** [comment]
Once the #742 I can give it a try. Multiple countries would be relatively easy, the concept of continents would require to place each country in their right continent, and that is not necesarilly trivial. I'll take a look anyway.

**Comment by scraly** [comment]
If you have some time @jespino I think it can be helpful :)

**Comment by scraly** [comment]
Fixes in #1077 :)
