### ISSUE TITLE
(add) CodeConnect Triple June 4-6

### ISSUE THREAD

**Issue by vobu** [scraly/developers-conferences-agenda#822]
3 SAP-related conferences back to back, codenamed "CodeConnect"   
all at the same location in Germany, ROT03, SAP Campus St. Leon Rot   
all hybrid: on-site and streamed   
- June 4: re>≡CAP (un)conference https://recap-conf.dev, CfP already running until end of Feb https://recap.cfapps.eu12.hana.ondemand.com   
- June 5: UI5con https://openui5.org/ui5con/germany2024/, CfP already running until end of Feb http://ui5con2024.cfapps.eu12.hana.ondemand.com   
- June 6: ABAPconf Europe

thanks for adding these!

**Comment by scraly** [comment]
I added re cap and ui5conf :) 

About ABAPconf it seems that the website is not working.
