### ISSUE TITLE
2024 events have CFP closing dates in 2023

### ISSUE THREAD

**Issue by peoray** [scraly/developers-conferences-agenda#833]
For most of the events for 2024, the CFP closing date is in 2023, mostly in December
<img width="1386" alt="Screenshot 2024-01-24 at 2 45 25 PM" src="https://github.com/scraly/developers-conferences-agenda/assets/23735423/4c3e7a9c-c509-4c3d-978d-f3bbd357b2bb">

**Comment by jespino** [comment]
Can you give more information about what is the problem there? There is a lot of events that close the CFP on December. Is the problem that are put in "green"? we need to update that in the readme, but I don't think this is an error, for example, pycon US 24 closed the CFP on December 2023 as you can see in the web page: https://us.pycon.org/2024/speaking/guidelines/

**Comment by peoray** [comment]
okay in that case, that's fine. I just assumed for a conference that's as far as May or even further, it was weird that the closing date is in December

**Comment by scraly** [comment]
Every conference choose if they open or not a CFP and when the CFP open and close :)

**Comment by scraly** [comment]
It's not weird to have a closing date in december.
The CFP close in december, so the program comitee will do the deliberation, speakers will be informed in january. The time to have all the accepted and refused information, the program will be published in february or march for example.

So it's not a lot of time for speakers to create or improve their talks and to people to watch the program and know if they want to buy a ticket or not :).
