### ISSUE TITLE
QCon San Francisco International Software Development Conference. Nov 18-22, 2024

### ISSUE THREAD

**Issue by ianrobins** [scraly/developers-conferences-agenda#837]
Title: QCon San Francisco International Software Development Conference. Nov 18-22, 2024. 
Short Title: QCon San Francisco 2024
Dates: Conference: Nov 18-20, 2024; Training: Nov 21-22, 2024
Venue: Hyatt Regency San Francisco, 5 Embarcadero Ctr, San Francisco, CA 94111, United States

Short Description:
QCon San Francisco is an international software development conference for senior software engineers, software architects, and team leads. 

Long Description:
QCon San Francisco is an international software development conference for senior software engineers, software architects, and team leads. 

Between November 18-22, senior software leaders driving innovation in software engineering and architecture will come together for 3 days of real-world technical talks, practical advice, and actionable insights. The conference will be followed by 2-days of hands-on training sessions, where you can deep-dive into specific topics and learn in an intimate setting.

Find practical inspiration (not product pitches) from software leaders deep in the trenches creating software, scaling architectures, and fine-tuning their technical leadership to help you make the right decisions. 

QCon San Francisco will focus on innovations and emerging trends in the software development industry. Deep-dive with world-class software leaders on the patterns, practices, and use cases leveraged by early adopter companies. Provisional topics covered at QCon San Francisco include: 
Architectures You've Always Wondered About
Innovations in Data Engineering
Connecting Systems: APIs, Protocols, Observability
Engineering Leadership for All
Cloud-Native Engineering
Platforms, People & Process; Delivering Great Developer Experiences
What's next in GenAI and Large Language Models (LLMs)
Emerging Trends in the Frontend and Mobile Development
Performance Engineering Unleashed: Powering Efficiency and Innovation
Securing Modern Software
Architecture for the Age of AI
Efficient Programming Languages

"QCon is the ONE event every software leader needs to attend to stay relevant.” 
Suresh Jeyachandran, Senior Management @DeNA & QCon San Francisco 2023 attendee

With practitioner-driven content, case studies, and in-depth technical talks, QCon will provide you with actionable insights and skills that you can take back to your teams.

At QCon, you’ll always find:
Senior software practitioners first.
Real-world technical talks.
No hidden marketing, no sales pitches, no hype.
Hand-picked speakers by an international program committee.
‘We Care’ experience: healthy food, strict code of conduct.

Attending QCon San Francisco provides a unique opportunity to learn, build connections, and explore one of the most vibrant and dynamic cities in the world. Connect with speakers and peers, attend group problem-solving unconference sessions, and join the conference social events. It's a chance to take your professional development to the next level while experiencing all that QCon San Francisco has to offer. 

Build better-connected teams in the heart of San Francisco.
QCon San Francisco brings together international software development teams to connect over new ideas to current challenges, get clarity on emerging tech decisions, and build relationships that extend beyond the conference.

Group discounts are available now. Join QCon as a team and save with exclusive discounts. For more details and to apply for a discount code, please contact [info@qconsf.com](mailto:info@qconsf.com) and mention the size of the group.

Level up on the topics that matter the most right now, solve your complex engineering challenges, and get clarity on software decisions, workflows, and roadmaps. Don’t miss out on real-world insights to help you adopt the right technologies and practices. 

Is your company interested in connecting with senior developers and decision-makers? Explore sponsorship opportunities by emailing [sales@qconferences.com](mailto:sales@qconferences.com). 

For all other inquiries, please email [info@qconsf.com](mailto:info@qconsf.com). 

Website Link: https://qconsf.com/medialisting2024 
Tickets Link: https://qconsf.com/medialisting2024/tickets  

Event inquiries: [info@qconsf.com](mailto:info@qconsf.com) 
Sales inquiries: [sales@qconferences.com](mailto:sales@qconferences.com)

Facebook: https://www.facebook.com/QCon/ 
LinkedIn: https://www.linkedin.com/company/qcon-conferences/ 
Instagram: https://www.instagram.com/qconconferences/ 
Flickr: https://www.flickr.com/photos/qconpictures/collections/ 
Mastodon: https://techhub.social/@qcon 

Press & Media Contact: 
Ian Robins
Marketing Director
C4Media, creators of InfoQ & QCon
Email: [ian.robins@c4media.com](mailto:ian.robins@c4media.com)
General Marketing Enquiries: [marketing@c4media.com](mailto:marketing@c4media.com)

About QCon by InfoQ: 
We've been helping software development teams adopt new technologies and practices for over 18 years. The driving force behind every QCon conference is our passion to accelerate the software side of human progress.

Senior software developers rely on QCon and InfoQ to keep ahead of the adoption curve. One of the main reasons senior software engineers, software architects, and team leads tell us they keep coming back to QCon and InfoQ is because they trust the information provided and selected by their peers. Join a global professional engineering community and adopt the right software innovations and practices.

**Comment by scraly** [comment]
added :)
