### ISSUE TITLE
Meetup Programmez! : frameworkless en Java

### ISSUE THREAD

**Issue by francoistonic** [scraly/developers-conferences-agenda#869]
Meetup Programmez! n°40 
On peut faire beaucoup de choses avec de simples librairies ou seulement le langage, sans utiliser de gros frameworks.
On garde le contrôle sur ce que l'on fait, on comprend mieux ce qui se passe et l'on apprend.

Les temps de démarrages sont réduits, l'empreinte mémoire également, et l'on diminue les coûts de maintenance.

Dans cette présentation, Hervé et Alban vous partagent leur façon d'utiliser l'ensemble de leur boite à outils, parce-que certains problèmes se règlent avec un tournevis et d'autres avec un marteau !

Hervé est un reconverti, ancien enseignant qui développe depuis 15 ans et responsable de la practice Java chez Meritis.
Alban a occupé de nombreux postes, développeur, architecte, techlead ces 15 dernières années et écrit régulièrement des articles de blog sur le monde java.

12 mars 2024
à partir de 18h30

Où : locaux de Meritis à Paris

lien : https://www.meetup.com/fr-FR/meetup-programmez/events/298563662/

**Comment by scraly** [comment]
Pour le moment je recense que les conferences tech, pas les meetups, mais il va falloir songer à voir comment lister ls meetups aussi:)
