### ISSUE TITLE
filter events with travel sponsorship

### ISSUE THREAD

**Issue by itaysk** [scraly/developers-conferences-agenda#876]
I know a lot of speakers that don't get employer support to travel to any conference, and some conferences that have an option to request travel funding (or partial). if would be useful to have this as a filter in the list
thanks for this awesome project

**Comment by scraly** [comment]
Hi
You already have this filter:
<img width="1407" alt="image" src="https://github.com/scraly/developers-conferences-agenda/assets/2543381/dfde6015-2f06-41b6-8a8e-0577657a7b8c">

:-)

**Comment by scraly** [comment]
Scholarship programs can contains ticket or ticket + travel or ticket + travel + hotel, depending on the conference, so I take in account global "scholarship" program :)

**Comment by itaysk** [comment]
ah sorry I saw the filter but assumed it was for conf ticket only. thanks!
