### ISSUE TITLE
Event listing submission:  InfoQ Dev Summit Munich. September 26-27, 2024. 

### ISSUE THREAD

**Issue by ianrobins** [scraly/developers-conferences-agenda#898]
Title: InfoQ Dev Summit Munich. September 26-27, 2024. 
Short Title:  InfoQ Dev Summit Munich 2024
Dates: Hilton Munich Park Hotel, Am Tucherpark 7, 80538 Munich, Germany

Short Description:
InfoQ Dev Summit Munich (September 26-27, 2024) is a two-day conference focusing on the most critical technical decisions senior software developers face today. Learn valuable real-world technical insights from 20+ senior software developers, build connections with speakers and peers, and unwind at social events.

Long Description:
InfoQ Dev Summit Munich (September 26-27, 2024) is a two-day conference focusing on the critical software priorities senior dev teams face today. Get transformative insights from 20+ senior software developers on navigating key topics like Generative AI, security, modern web applications, and more. Build connections with a senior developer community and unwind at social events.

Attend InfoQ Dev Summit Munich 2024 to learn:
Strategies to tackle current development challenges directly from senior software developers
Proven tactics and experiences to support dev prioritization
Innovative approaches and ideas to guide your projects
Actionable insights to guide critical decision-making

A focus on learning, not being sold to. 
We prioritize genuine learning experiences free from hidden marketing or sales pitches. Our focus is on real-world talks from senior software developers to facilitate collaborative learning and informed decision-making. Connect with speakers and peers during breaks and social activities to explore how they address challenges. 

Team discounts.
Attending InfoQ Dev Summit Munich as a team empowers collaborative learning, leading to informed project decisions and clarity for your dev roadmap. Teams as small as 3 attendees working for the same company are eligible for a group discount. For more details, email [info@devsummit.infoq.com](mailto:info@devsummit.infoq.com) and mention the size of the group.

The InfoQ Dev Summit Munich creates a unique opportunity for senior software developers to learn transformative insights directly impacting their immediate development roadmap and decision-making processes.

Please feel free to contact us with any questions at [info@devsummit.infoq.com](mailto:info@devsummit.infoq.com)

Website Link: https://devsummit.infoq.com/munich_medialisting2024  
Tickets Link: https://devsummit.infoq.com/munich_medialisting2024/tickets    

Event inquiries: [info@devsummit.infoq.com](mailto:info@devsummit.infoq.com)
Sales inquiries: [sales@devsummit.infoq.com](mailto:sales@devsummit.infoq.com) 

Facebook: https://www.facebook.com/InfoQdotcom 
LinkedIn: https://www.linkedin.com/company/infoq/ 
Instagram: https://www.instagram.com/infoqdotcom/ 
Mastodon: https://techhub.social/@infoq 

Press & Media Contact: 
Ian Robins
Marketing Director
C4Media, creators of InfoQ & QCon
Email: [ian@c4media.com](mailto:ian@c4media.com)  
General Marketing Enquiries: [marketing@c4media.com](mailto:marketing@c4media.com)

About Infoq Dev Summit Munich by InfoQ: 
InfoQ presents InfoQ Dev Summit Munich. For over 18 years, InfoQ has guided senior software development teams with peer-validated, trustworthy insights in adopting new technologies and practices.

**Comment by scraly** [comment]
Added :)
