### ISSUE TITLE
CFP Submission - Cypress Conf 2024

### ISSUE THREAD

**Issue by CY-Ronald** [scraly/developers-conferences-agenda#915]
We are excited to announce that the Call for Papers for CypressConf 2024 is now open. CypressConf is an annual conference that brings together industry experts, thought leaders, and innovators in the field of test automation with Cypress. As a speaker, you have the opportunity to share your knowledge and insights with a diverse audience of professionals.

Please note that all presentations at CypressConf 2024 will be scheduled for a duration of 15 minutes to 60 minutes. We encourage you to plan your talk accordingly, keeping in mind the need to deliver a comprehensive and engaging session within this timeframe.

Submission deadline: April 17th
Speaker confirmation: June 1st 
CypressConf Event: October 22nd & 23rd

If you have any questions or require additional information, please feel free to reach out to our event team at community@cypress.io. He will be more than happy to assist you with any queries you may have.

https://forms.gle/Vp7df4UHcCPHL1MCA

**Comment by scraly** [comment]
fixed
