### ISSUE TITLE
ABP Dotnet Conference 2024

### ISSUE THREAD

**Issue by bigebesikci** [scraly/developers-conferences-agenda#916]
Hi admins,

We are planning to meet with the .NET enthusiasts in ABP Dotnet Conference 2024 once again this year.

There will be 25+ speakers to talk about their experience on .NET world in this 2-day event with workshops and talks.

Event Name: ABP Dotnet Conference 2024
Event Date: 8-9 May 2024
Event Location: Online
Event Website: https://abp.io/conference/2024

Thank you. 🙏

Please let me know if you have any prior questions to include our event in your calendar.

I appreciate it.

**Comment by scraly** [comment]
I included the event :)
